# Generated by Django 3.1 on 2020-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('date_ajout', models.DateField()),
                ('date_modification', models.DateField()),
                ('date_suppression', models.DateField()),
                ('nom_court', models.CharField(max_length=100)),
                ('nom_long', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('texte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('corrige', models.BooleanField()),
                ('visibilite', models.IntegerField()),
                ('informations', models.TextField()),
                ('code_aperçu', models.CharField(max_length=50)),
                ('mots_cles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_document', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
